### ISSUE TITLE
Ignore multiple Files scan

### ISSUE THREAD

**Issue by rafaelsilvaa10** [lirantal/detect-secrets#15]
Hello, I am trying to ignore multiple files in my scan.

I have two files that are generated in build

```
**package-lock.json** 
      {
        "hashed_secret": "b9509cb72e127330340c248f2e104ef2d55fbf0d",
        "is_verified": false,
        "line_number": 9011,
        "type": "Base64 High Entropy String"
      },
```

**/assets/styles/font-awesome.min.css**

```
      {
        "hashed_secret": "91c33027fc97e826031e8cad0099ed498746f17d",
        "is_verified": false,
        "line_number": 4,
        "type": "Secret Keyword"
      }
```

how can i ignore these files?

I am tried 
`detect-secrets scan  . --exclude-files='package-lock.json, /assets/styles/font-awesome.min.css'`

**Comment by lirantal** [comment]
Did you create already a baseline with the `audit` flag?

Good idea to always seek help in the actual package which is here: https://github.com/Yelp/detect-secrets since this is just my npm wrapper around it.

**Comment by s1mrankaur** [comment]
same issue

**Comment by s1mrankaur** [comment]
@rafaelsilvaa10  Were you able to figure this out?

**Comment by lirantal** [comment]
@rafaelsilvaa10  @s1mrankaur can you try the syntax as follows:

```
detect-secrets scan . --exclude-files 'package-lock.json' --exclude-files '.*/assets/styles/font-awesome.min.css'
```

See here for the official docs: https://github.com/Yelp/detect-secrets#--exclude-files
Also FYI that I pushed a new docker image, so if you're using it you want to pull it again and test.
