### ISSUE TITLE
What should .secrets.baseline look like?

### ISSUE THREAD

**Issue by s1mrankaur** [lirantal/detect-secrets#16]
I am trying to have detect-secrets ignore the package-lock.json file 

This is what is my .secrets.baseline file looks like: This is the entire file

`{
  "exclude": {
    "files": ".trufflehog/rules.json|.env.*|.env|^.secrets.baseline$",
    "lines": null
  }
}
`

Is this not correct?

I tried to run` detect-secrets-launcher --baseline .secrets.baseline
`
hoping it will ignore the excluded file but I instead got:

$ detect-secrets-launcher --baseline .secrets.baseline
```

usage: detect-secrets-hook [-h] [-v] [--version] [--baseline FILENAME]
                           [--list-all-plugins] [-p PLUGIN]
                           [--base64-limit [BASE64_LIMIT]]
                           [--hex-limit [HEX_LIMIT]]
                           [--disable-plugin DISABLE_PLUGIN]
                           [-n | --only-verified]
                           [--exclude-lines EXCLUDE_LINES]
                           [--exclude-files EXCLUDE_FILES]
                           [--exclude-secrets EXCLUDE_SECRETS] [-f FILTER]
                           [--disable-filter DISABLE_FILTER]
                           [filenames [filenames ...]]
error: Invalid baseline.

```

**Comment by lirantal** [comment]
`.secrets.baseline` is autogenerated.

I answered something similar in https://github.com/lirantal/detect-secrets/issues/15#issuecomment-825576350
