### ISSUE TITLE
version of detect-secrets on the build of dockerhub is outdated

### ISSUE THREAD

**Issue by belaaiza** [lirantal/detect-secrets#17]
## Expected Behavior

The lib should install the latest version of detect-secrets on docker. 

## Current Behavior

If I run the image installed by the lib with `/bin/bash` as entrypoint and run `detect-secrets --version`, it shows the version 1.0.3, which is not the latest version of detect-secrets.

<img width="1568" alt="Captura de Tela 2021-05-05 às 16 25 05" src="https://user-images.githubusercontent.com/14032043/117197940-c676d480-adbe-11eb-837e-934d51669f60.png">

## Possible Solution

I think that the image should be rebuild and updated on dockerhub.

## Steps to Reproduce (for bugs)

1. `npm instal --save-dev detect-secrets`
2. `npx detect-secrets (git ls-files)`
3. `docker run --entrypoint /bin/bash -it lirantal/detect-secrets`
4. `detect-secrets --version`

## Context

The latest version ignores the package-lock.json file, it would be nice to have this feature.

## Your Environment

- Library Version used: 1.0.6
- Node.js version (e.g. Node.js 5.4): 12.13.1
- Operating System and version (desktop or mobile): MacOS

**Comment by belaaiza** [comment]
@lirantal can you update the image on docker hub?

**Comment by lirantal** [comment]
@belaaiza looking into it now

**Comment by lirantal** [comment]
@belaaiza new image pushed with latest 1.1.0 from yelp: 
![image](https://user-images.githubusercontent.com/316371/117494636-4480da00-af7d-11eb-98fa-256edccdf700.png)

Thank you for the reminder to update :-)
