### ISSUE TITLE
How can I ignore a folder?

### ISSUE THREAD

**Issue by fabidick22** [lirantal/detect-secrets#6]
How can I ignore the `node_modules` folder?

**Comment by fabidick22** [comment]
I'm trying this, but it doesn't work..

`.secrets.baseline`
```json
...
"exclude": {
    "files": ".*/node_modules/.*",
    "lines": null
  },
...
```

**Comment by lirantal** [comment]
It should only scan files that are known to git so I assume you have `node_modules/` committed to git? If so, is that by a chance? as it probably shouldn't be the case commonly.

**Comment by fabidick22** [comment]
Yes, I have `node_modules` in my `.gitignore` file..

**Comment by lirantal** [comment]
So detect-secrets shouldn't pick any files in the `node_modules/` directory. Only files that are tracked with git are being tested for sensitive data.
